### PR TITLE
Aseba target Elisa-3

### PR DESCRIPTION
**Pull request by gctronic**
Updated version.

### CODE REVIEW

**Comment by stephanemagnenat** [comment]
Please do not includes copy of Aseba in targets. If you want something simple to deploy, I suggest using submodules (see for instance https://git-scm.com/docs/git-submodule). You can see an example this repository https://github.com/aseba-community/thymio-ar.

Also, please include a top-level readme that explains why there is currently only an elisa3 directory and also gives high-level instructions on how to compile this target.

I have one further question: are all files in `elisa3/default` necessary? Are some temporary files? It seems to me that too much local files have been included in the git tree.

**Comment by gctronic** [comment]
Hi,
the code is updated.
Best regards,

Stefano

Il 01.02.2016 14:06, Stéphane Magnenat ha scritto:

> Please do not includes copy of Aseba in targets. If you want something 
> simple to deploy, I suggest using submodules (see for instance 
> https://git-scm.com/docs/git-submodule). You can see an example this 
> repository https://github.com/aseba-community/thymio-ar.
> 
> Also, please include a top-level readme that explains why there is 
> currently only an elisa3 directory and also gives high-level 
> instructions on how to compile this target.
> 
> I have one further question: are all files in |elisa3/default| 
> necessary? Are some temporary files? It seems to me that too much 
> local files have been included in the git tree.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/aseba-community/aseba-targets-arduino/pull/1#issuecomment-177965350.

## 

Stefano Morgani
GCtronic Sagl, Electronics & Mechatronics
web: www.gctronic.com E-mail: stefano@gctronic.com

---

Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by stephanemagnenat** [comment]
Hi Stefano,

It is better :-) I still have some comments:
- please rebase the pull request so that the temporary files are not in the history
- Is the file `elisa3/.vs/elisa3-aseba/v14/.atsuo` necessary?
- The file `elisa3/elisa3-aseba.aws` has local paths and therefore is probably unusable for third parties.
- There are some visual studio files (for instance `elisa3/elisa3-aseba.atsln`). Are they useful in the git? Are you compiling using visual studio? Some such as `elisa3/elisa3-aseba.componentinfo.xml` have local paths inside.

cheers,

Stéphane

**Comment by gctronic** [comment]
Hi, the code is updated. Best regards, Stefano

**Pull request merged**
